### ISSUE TITLE
Pre-build docs?

### ISSUE THREAD

**Issue by TheZoq2** [lithekod/snake-ribs#14]
The documentation is obviously best viewed in the browser. To do so users need to build the docs and open the resulting file in the browser. It might be easiest to pre-build it and host it on github pages to avoid having to describe that process.

**Comment by FredTheDino** [comment]
I was thinking of just hosting it on the lithekod server somewhere. And link to that, but I do like your idea of hosting it on github, it is fewer steps! :+1:

**Comment by TheZoq2** [comment]
If we want to, we could point lithekod.se/snake-ribs or something here

**Comment by FredTheDino** [comment]
Already put @EMattfolk on that. Hopefully it'll be done soon, but now since everything is just build automatically, it's gonna be a breeze!

**Comment by EMattfolk** [comment]
It has been done. [https://lithekod.se/snake-ribs](https://lithekod.se/snake-ribs)
