### ISSUE TITLE
Overview documentation

### ISSUE THREAD

**Issue by TheZoq2** [lithekod/snake-ribs#18]
I think we should have something at the top of the docs page with
- What is snake ribs
- Docs link for pygame
- How to read these docs
    - Argument lists
    - Keyword arguments
    - Something else?
- How is a common snake-ribs game structured

I can get started writing something like that

**Comment by FredTheDino** [comment]
Great! I've reviewed some of the PRs, let me know if you want me to write any of those sections, and I'll be happy to help
